# Generated by Django 5.0.9 on 2024-09-29 16:41

from django.db import migrations, models
import uuid


def populate_uuids(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(uuid__isnull=True):
        user.uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_user_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_uuids, reverse_code=migrations.RunPython.noop),
    ]
